// SPDX-License-Identifier: BUSL-1.1
// AUTO-GENERATED by tools/scripts/select-chain-config.js — DO NOT EDIT BY HAND.
// Active chain: test
pragma solidity 0.8.17;

/**
 * DeploymentChainConfig
 * The single source of chain-specific constants consumed by DeploymentConstants.
 * Regenerate with: node tools/scripts/select-chain-config.js <test|avalanche|arbitrum>
 * Default checked-in state is "test" (local Forge fixtures deployCodeTo() at these
 * addresses). CI verifies this file matches its generator (--check mode).
 **/
library DeploymentChainConfig {
    string internal constant CHAIN_KEY = "test";

    bytes32 internal constant NATIVE_TOKEN_SYMBOL = 'AVAX';
    address internal constant NATIVE_ADDRESS = 0x9Ab9C8E027B97AF7d3eA7eD59E108b3EE6748938;
    address internal constant DIAMOND_BEACON = 0x09E82d532fc72B8e105F17104a12C827de7E20dD;
    address internal constant SMART_LOANS_FACTORY = 0xf77FaCdD1309EC6867682BcE2c93Fb94e22A0EA9;
    address internal constant TOKEN_MANAGER = 0xEC72E57Af0b26abfC31575e7BdCc182A506a9627;
    address internal constant ADDRESS_PROVIDER = 0x5e26DB3DCe603dc3C092BF5Bf1d9acb0D2dB9f7C;
    address internal constant FEES_TREASURY = 0x87Cd4631A80245C00b318A6AE5a5Ef1b67BE2515;
    address internal constant STABILITY_POOL = 0xaAc5F9fD435D602f52312A6389f0009B3a49385D;
    address internal constant GMX_DATA_STORE = 0x5497dbEc013b31475c57eD92ae4097AA357c54dA;
    address internal constant GMX_READER = 0xbb1480C292bEd789f6490166E584Ae6ad4A701d5;
    address internal constant GLV_READER = 0x584C2fe46dfa44ffb60548BE11a52ef9f6d06EEA;
    address internal constant DEPOSIT_SWAP = 0x6C6C362A39d06937234ce908751DFf71Dface543;
}
